server:
  port: 5020
  servlet.context-path: /ms-auth/

spring:
  application.name: ms-auth
  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false
  session.store-type: redis # 存放session的存储方式-redis
  cloud:
    nacos:
      discovery:
        ephemeral: false
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ms-auth?serverTimezone=GMT
    username: root
    password: Abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: 127.0.0.1
    port: 6379
    password:
